apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev
namePrefix: dev-
commonLabels:
  environment: dev
  version: v1.0.0

resources:
- ../../base/demo-app/

patchesStrategicMerge:
- deployment-patch.yaml
- ingress-patch.yaml

images:
- name: nginx:alpine
  newTag: 1.21-alpine
