apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-nginx-config
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        server {
            listen       80;
            server_name  localhost;
            root   /usr/share/nginx/html;

            location / {
                index  index.html index.htm;
            }

            location = /health {
                add_header Content-Type application/json;
                return 200 '{"status": "healthy", "timestamp": "$time_local"}';
            }

            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   /usr/share/nginx/html;
            }
        }
    }
