apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod
namePrefix: prod-
commonLabels:
  environment: production
  version: v1.0.0

resources:
- ../../base/demo-app/

patchesStrategicMerge:
- deployment-patch.yaml
- ingress-patch.yaml

images:
- name: nginx:alpine
  newTag: 1.23-alpine

replicas:
- name: demo-app
  count: 3
