apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod

resources:
- ../../base/demo-app

patchesStrategicMerge:
- deployment-patch.yaml
- configmap-patch.yaml

commonLabels:
  environment: production
