apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
- ../../base/demo-app/

patchesStrategicMerge:
- deployment-patch.yaml

images:
- name: nginx:alpine
  newTag: alpine

replicas:
- name: demo-app
  count: 3
