apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-certificates
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shahat112/k8s-production-config.git
    targetRevision: HEAD
    path: .
    directory:
      include: |
        *ingress*.yaml
        *certificate*.yaml
        letsencrypt-clusterissuer.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
